"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/ljMRW8ysNr6
 */
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuRadioItem, DropdownMenuRadioGroup, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { Input } from "@/components/ui/input"
import { ResponsiveScatterPlot } from "@nivo/scatterplot"

export function datasetcreator() {
  return (
    <div className="grid gap-4">
      <div className="flex items-center gap-4">
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button className="w-[180px] justify-between text-left" size="sm" variant="outline">
              <span className="truncate">Lotka-Volterra</span>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuLabel>System</DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuRadioGroup defaultValue="lotka-volterra">
              <DropdownMenuRadioItem value="lotka-volterra">Lotka-Volterra</DropdownMenuRadioItem>
              <DropdownMenuRadioItem value="lorenz">Lorenz</DropdownMenuRadioItem>
              <DropdownMenuRadioItem value="pendulum">Pendulum</DropdownMenuRadioItem>
            </DropdownMenuRadioGroup>
          </DropdownMenuContent>
        </DropdownMenu>
        <Input className="w-[200px]" placeholder="Enter number of simulations" />
        <Button className="h-9">Plot System</Button>
      </div>
    </div>
  )
}

