name: PublishToTestPyPI

on: #trigger event
  pull_request:
    branches:
      - dev/update_to_1.4.2_automate_publishing

jobs:
  build:
    name: Builddistribution
    #if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3


    - name: Get the latest tag
      id: get_tag
      run: echo ::set-output name=VERSION::$(git describe --tags --abbrev=0 | sed 's/^v//')

    - name: Update version in pyproject.toml
      run: sed -i "s/version = .*/version = \"${{ steps.get_tag.outputs.VERSION }}\"/" pyproject.toml

    - name: Install pypa/build
      run: | 
        pip install build --user
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-testpypi:
    name: Publish
    #if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/neuromancer-test

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  